plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.YucelDigital.ilactakip'
    compileSdk 36

    defaultConfig {
        applicationId "com.YucelDigital.ilactakip"
        minSdk 24
        targetSdk 36
        versionCode 3
        versionName "3.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }
}

dependencies {
    implementation libs.appcompat
    implementation 'com.google.code.gson:gson:2.10.1'
    implementation libs.material
    implementation libs.activity
    implementation libs.constraintlayout
    testImplementation libs.junit
    testImplementation 'org.robolectric:robolectric:4.14.1'
    testImplementation 'androidx.test:core:1.6.1'
    androidTestImplementation libs.ext.junit
    androidTestImplementation libs.espresso.core
}